name: flutter_firebase_quiz_app
description: A new end-to-end Flutter project with firebase and riverpod

publish_to: 'none'

version: 0.0.1+1

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  # ui
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  # development
  very_good_analysis: ^3.1.0

flutter:

  uses-material-design: true
